apiVersion: apps/v1
kind: Deployment
metadata:
  name: CALL
  labels:
    app: CALL
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CALL
  template:
    metadata:
      labels:
        app: CALL
    spec:
      containers:
        - name: CALL
          image: username/CALL:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5