---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: CALL
  labels:
    app: CALL
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CALL
  template:
    metadata:
      labels:
        app: CALL
    spec:
      containers:
        - name: CALL
          image: username/CALL:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: TAXI
  labels:
    app: TAXI
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TAXI
  template:
    metadata:
      labels:
        app: TAXI
    spec:
      containers:
        - name: TAXI
          image: username/TAXI:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: NOTIFY
  labels:
    app: NOTIFY
spec:
  replicas: 1
  selector:
    matchLabels:
      app: NOTIFY
  template:
    metadata:
      labels:
        app: NOTIFY
    spec:
      containers:
        - name: NOTIFY
          image: username/NOTIFY:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: SMS
  labels:
    app: SMS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SMS
  template:
    metadata:
      labels:
        app: SMS
    spec:
      containers:
        - name: SMS
          image: username/SMS:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: PAYMENT
  labels:
    app: PAYMENT
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PAYMENT
  template:
    metadata:
      labels:
        app: PAYMENT
    spec:
      containers:
        - name: PAYMENT
          image: username/PAYMENT:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: MEMBERSHIP
  labels:
    app: MEMBERSHIP
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MEMBERSHIP
  template:
    metadata:
      labels:
        app: MEMBERSHIP
    spec:
      containers:
        - name: MEMBERSHIP
          image: username/MEMBERSHIP:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: TAXISERVICEVIWER
  labels:
    app: TAXISERVICEVIWER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TAXISERVICEVIWER
  template:
    metadata:
      labels:
        app: TAXISERVICEVIWER
    spec:
      containers:
        - name: TAXISERVICEVIWER
          image: username/TAXISERVICEVIWER:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: CALL
  labels:
    app: CALL
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: CALL


---


apiVersion: v1
kind: Service
metadata:
  name: TAXI
  labels:
    app: TAXI
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: TAXI


---


apiVersion: v1
kind: Service
metadata:
  name: NOTIFY
  labels:
    app: NOTIFY
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: NOTIFY


---


apiVersion: v1
kind: Service
metadata:
  name: SMS
  labels:
    app: SMS
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: SMS


---


apiVersion: v1
kind: Service
metadata:
  name: PAYMENT
  labels:
    app: PAYMENT
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: PAYMENT


---


apiVersion: v1
kind: Service
metadata:
  name: MEMBERSHIP
  labels:
    app: MEMBERSHIP
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: MEMBERSHIP


---


apiVersion: v1
kind: Service
metadata:
  name: TAXISERVICEVIWER
  labels:
    app: TAXISERVICEVIWER
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: TAXISERVICEVIWER

